# Generated by Django 5.0.4 on 2024-05-05 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Objeto',
            fields=[
                ('id_objeto', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('nombre_objeto', models.CharField(max_length=100)),
                ('cantidad_objeto', models.IntegerField()),
                ('tipo_objeto', models.CharField(max_length=100)),
                ('fecha_objeto', models.DateField(auto_now_add=True)),
                ('img', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id_usuario', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('nombre_usuario', models.CharField(max_length=100)),
                ('correo', models.CharField(default='ejemplo@gmail.com', max_length=200)),
                ('celular', models.IntegerField()),
                ('sexo', models.CharField(blank=True, choices=[('F', 'Femenino'), ('M', 'Masculino')], default=' ', max_length=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Edificio',
            fields=[
                ('id_edificio', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('nombre_edificio', models.CharField(default='Cedro/Lago/Cafeteria', max_length=50)),
                ('id_objeto_edificio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto_app.objeto')),
            ],
        ),
    ]
