# Generated by Django 5.0.4 on 2024-05-05 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='contraseña',
            field=models.CharField(default='DEFAULT VALUE', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='objeto',
            name='fecha_objeto',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='objeto',
            name='img',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='correo',
            field=models.CharField(default='ejemplo@gmail.com', max_length=200, null=True),
        ),
    ]
