# Generated by Django 5.0.4 on 2024-05-06 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto_app', '0002_usuarios_contraseña_alter_objeto_fecha_objeto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='objeto',
            name='lugar_perdiad',
            field=models.CharField(default='DEFAULT VALUE', max_length=100),
        ),
    ]
