# Generated by Django 5.0.4 on 2024-05-07 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto_app', '0004_alter_usuarios_sexo'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='time_create',
            field=models.DateTimeField(null=True),
        ),
    ]
