# Generated by Django 5.0.4 on 2024-05-07 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto_app', '0005_usuarios_time_create'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='time_create',
            field=models.DateTimeField(auto_created=True, blank=True, null=True),
        ),
    ]
