# Generated by Django 5.0.4 on 2024-05-09 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto_app', '0006_alter_usuarios_time_create'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('date_joined', models.DateTimeField(auto_created=True, blank=True, null=True)),
                ('last_login', models.DateTimeField(auto_created=True, blank=True, null=True)),
                ('id_user', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(default='ejemplo@gmail.com', max_length=200, null=True)),
                ('password', models.CharField(default='DEFAULT VALUE', max_length=50, unique=True)),
                ('phone', models.IntegerField()),
                ('sexo', models.CharField(blank=True, default=' ', max_length=1, null=True)),
                ('is_staff', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Usuarios',
        ),
    ]
