# Generated by Django 5.0.4 on 2024-06-04 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto_app', '0009_alter_objeto_fecha_objeto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objeto',
            name='fecha_objeto',
            field=models.DateField(),
        ),
    ]
