# Generated by Django 5.0.4 on 2024-06-04 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto_app', '0010_alter_objeto_fecha_objeto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='objeto',
            name='fecha_objeto',
        ),
    ]
